package com.rixon.projecteuler.main;

import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

/**
 * Created by rixonmathew on 01/04/15.
 */
public class FibbonacciSumTest {
    /**
     * problem definition
     *
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
     *       1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     *   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
     */

    private FibbonaciSumComputer fibbonaciSumComputer;

    @Before
    public void setup() {
        fibbonaciSumComputer = new FibbonaciSumComputer();
    }

    @Test
    public void testSumOfFirst10EvenValuedTerms() {
        //1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597,2284,
        //6 even terms - 2+8+34+144+610+2284
        long expectedSum = 4613732l;
        long actualSum = fibbonaciSumComputer.sumOfFirstEvenTerms(11);
        assertEquals("Count does not match",expectedSum,actualSum);
    }
}
